# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/EE301579301549CB/Unreal Engine/Linux_Unreal_Engine_5.5.0

TARGETS = \
	CryptRaider-Android-DebugGame  \
	CryptRaider-Android-Development  \
	CryptRaider-Android-Shipping  \
	CryptRaider-Linux-DebugGame  \
	CryptRaider-Linux-Development  \
	CryptRaider-Linux-Shipping  \
	CryptRaider-LinuxArm64-DebugGame  \
	CryptRaider-LinuxArm64-Development  \
	CryptRaider-LinuxArm64-Shipping  \
	CryptRaider \
	CryptRaiderEditor-Linux-DebugGame  \
	CryptRaiderEditor-Linux-Development  \
	CryptRaiderEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend CryptRaiderEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug CryptRaiderEditor-Linux-Debug


CryptRaider-Android-DebugGame:
	 $(BUILD) CryptRaider Android DebugGame  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider-Android-Development:
	 $(BUILD) CryptRaider Android Development  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider-Android-Shipping:
	 $(BUILD) CryptRaider Android Shipping  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider-Linux-DebugGame:
	 $(BUILD) CryptRaider Linux DebugGame  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider-Linux-Development:
	 $(BUILD) CryptRaider Linux Development  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider-Linux-Shipping:
	 $(BUILD) CryptRaider Linux Shipping  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider-LinuxArm64-DebugGame:
	 $(BUILD) CryptRaider LinuxArm64 DebugGame  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider-LinuxArm64-Development:
	 $(BUILD) CryptRaider LinuxArm64 Development  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider-LinuxArm64-Shipping:
	 $(BUILD) CryptRaider LinuxArm64 Shipping  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaider: CryptRaider-Linux-Development

CryptRaiderEditor-Linux-DebugGame:
	 $(BUILD) CryptRaiderEditor Linux DebugGame  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaiderEditor-Linux-Development:
	 $(BUILD) CryptRaiderEditor Linux Development  -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" $(ARGS)

CryptRaiderEditor: CryptRaiderEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/tanisha-kothari/Documents/Unreal Projects/CryptRaider/CryptRaider.uproject" -Game 

.PHONY: $(TARGETS)
